export const ErrorCodes = {
  // Authentication errors
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',

  // User management errors
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_CANNOT_DELETE_SELF: 'USER_CANNOT_DELETE_SELF',
  USER_CANNOT_EDIT_OWN_PERMISSIONS: 'USER_CANNOT_EDIT_OWN_PERMISSIONS',

  // Server management errors
  SERVER_NOT_FOUND: 'SERVER_NOT_FOUND',
  SERVER_ALREADY_RUNNING: 'SERVER_ALREADY_RUNNING',
  SERVER_NOT_RUNNING: 'SERVER_NOT_RUNNING',
  SERVER_ALREADY_STOPPING: 'SERVER_ALREADY_STOPPING',
  SERVER_START_FAILED: 'SERVER_START_FAILED',
  SERVER_STOP_FAILED: 'SERVER_STOP_FAILED',
  SERVER_DIR_NOT_FOUND: 'SERVER_DIR_NOT_FOUND',
  SERVER_JAR_NOT_FOUND: 'SERVER_JAR_NOT_FOUND',
  SERVER_MUST_BE_STOPPED: 'SERVER_MUST_BE_STOPPED',
  SERVER_PORT_ALREADY_IN_USE: 'SERVER_PORT_ALREADY_IN_USE',
  SERVER_JAVA_NOT_FOUND: 'SERVER_JAVA_NOT_FOUND',
  SERVER_BACKUP_FAILED: 'SERVER_BACKUP_FAILED',
  SERVER_DELETE_FAILED: 'SERVER_DELETE_FAILED',

  // File system errors
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_ACCESS_DENIED: 'FILE_ACCESS_DENIED',
  FILE_PATH_TRAVERSAL: 'FILE_PATH_TRAVERSAL',
  FILE_ALREADY_EXISTS: 'FILE_ALREADY_EXISTS',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_NOT_A_DIRECTORY: 'FILE_NOT_A_DIRECTORY',
  FILE_IS_A_DIRECTORY: 'FILE_IS_A_DIRECTORY',
  FILE_CANNOT_DELETE_ROOT: 'FILE_CANNOT_DELETE_ROOT',

  // Onboarding errors
  SETUP_ALREADY_COMPLETED: 'SETUP_ALREADY_COMPLETED',

  // TOTP 2FA errors
  TOTP_ALREADY_ENABLED: 'TOTP_ALREADY_ENABLED',
  TOTP_NOT_ENABLED: 'TOTP_NOT_ENABLED',
  TOTP_INVALID_CODE: 'TOTP_INVALID_CODE',
  TOTP_SETUP_REQUIRED: 'TOTP_SETUP_REQUIRED',

  // Firewall errors
  FIREWALL_RULE_EXISTS: 'FIREWALL_RULE_EXISTS',
  FIREWALL_RULE_NOT_FOUND: 'FIREWALL_RULE_NOT_FOUND',
  FIREWALL_SCRIPT_FAILED: 'FIREWALL_SCRIPT_FAILED',
  FIREWALL_PORT_RESERVED: 'FIREWALL_PORT_RESERVED',

  // Task errors
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',

  // General errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
