import { z } from 'zod';
import { resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const APP_DIR = resolve(__filename, '../..');
const SHULKR_HOME_DEFAULT = '/opt/shulkr';

const trustProxyTransform = (raw: string | undefined): boolean | Array<string> => {
  if (raw === undefined || raw === '') return ['127.0.0.1', '::1'];

  try {
    const parsed: unknown = JSON.parse(raw);
    if (typeof parsed === 'boolean') return parsed;
    if (Array.isArray(parsed) && parsed.every((v) => typeof v === 'string')) return parsed;
    throw new Error('TRUST_PROXY must be a boolean or an array of strings (JSON)');
  } catch (err) {
    throw new Error(`TRUST_PROXY: invalid JSON value: ${err instanceof Error ? err.message : String(err)}`, { cause: err });
  }
};

const csvTransform = (raw: string | undefined): Array<string> => {
  if (!raw) return ['http://localhost:3000', 'http://localhost:5173'];

  return raw
    .split(',')
    .map((entry) => entry.trim())
    .filter(Boolean);
};

export const appConfigSchema = z.object({
  NODE_ENV: z.enum(['development', 'production', 'test']).default('development'),
  LOG_LEVEL: z.enum(['trace', 'debug', 'info', 'warn', 'error', 'fatal', 'silent']).default('info'),
  PORT: z.coerce.number().int().min(1).max(65535).default(3001),

  // Filesystem layout
  SHULKR_HOME: z.string().default(SHULKR_HOME_DEFAULT),
  SERVERS_BASE_PATH: z.string().optional(),
  BACKUPS_BASE_PATH: z.string().optional(),
  DATABASE_PATH: z.string().optional(),

  // Secrets (auto-generated by env.ts when missing)
  JWT_SECRET: z.string().min(16, 'JWT_SECRET is required and must be at least 16 chars'),
  COOKIE_SECRET: z.string().min(16, 'COOKIE_SECRET is required and must be at least 16 chars'),
  // Lazy-validated by totp_service when 2FA is actually used; absence at boot is tolerated.
  TOTP_ENCRYPTION_KEY: z.string().min(16, 'TOTP_ENCRYPTION_KEY must be at least 16 chars when set').optional(),

  // Optional encryption key override
  SHULKR_ENCRYPTION_KEY: z.string().optional(),
  SHULKR_ENCRYPTION_KEY_PATH: z.string().optional(),

  // CORS / cookies
  CORS_ORIGIN: z.string().optional().transform(csvTransform),
  SECURE_COOKIES: z
    .union([z.literal('true'), z.literal('false')])
    .default('false')
    .transform((v) => v === 'true'),
  TRUST_PROXY: z.string().optional().transform(trustProxyTransform),

  // External shell scripts
  FIREWALL_SCRIPT_PATH: z.string().optional(),
  SFTP_SCRIPT_PATH: z.string().optional(),
  DOMAIN_SCRIPT_PATH: z.string().optional(),

  // Agent
  SHULKR_AGENT_BACKEND_URL: z.string().url().default('http://127.0.0.1:3001'),

  // Test-only knobs (no effect in dev/prod)
  SHELL_DRY_RUN: z
    .union([z.literal('true'), z.literal('false')])
    .default('false')
    .transform((v) => v === 'true'),
});

export type AppConfig = Omit<
  z.infer<typeof appConfigSchema>,
  'SERVERS_BASE_PATH' | 'BACKUPS_BASE_PATH' | 'DATABASE_PATH' | 'FIREWALL_SCRIPT_PATH' | 'SFTP_SCRIPT_PATH' | 'DOMAIN_SCRIPT_PATH'
> & {
  SERVERS_BASE_PATH: string;
  BACKUPS_BASE_PATH: string;
  DATABASE_PATH: string;
  FIREWALL_SCRIPT_PATH: string;
  SFTP_SCRIPT_PATH: string;
  DOMAIN_SCRIPT_PATH: string;
};

export function parseConfig(env: NodeJS.ProcessEnv): AppConfig {
  const parsed = appConfigSchema.safeParse(env);

  if (!parsed.success) {
    const issues = parsed.error.issues.map((i) => `  - ${i.path.join('.')}: ${i.message}`).join('\n');
    throw new Error(`Invalid environment configuration:\n${issues}`);
  }

  const cfg = parsed.data;
  const SHULKR_HOME = cfg.SHULKR_HOME;

  return {
    ...cfg,
    SERVERS_BASE_PATH: cfg.SERVERS_BASE_PATH ?? join(SHULKR_HOME, 'servers'),
    BACKUPS_BASE_PATH: cfg.BACKUPS_BASE_PATH ?? join(SHULKR_HOME, 'backups'),
    DATABASE_PATH: cfg.DATABASE_PATH ?? join(SHULKR_HOME, 'data', 'shulkr.db'),
    FIREWALL_SCRIPT_PATH: cfg.FIREWALL_SCRIPT_PATH ?? resolve(APP_DIR, 'scripts/subs/subs_firewall.sh'),
    SFTP_SCRIPT_PATH: cfg.SFTP_SCRIPT_PATH ?? resolve(APP_DIR, 'scripts/subs/subs_sftp.sh'),
    DOMAIN_SCRIPT_PATH: cfg.DOMAIN_SCRIPT_PATH ?? resolve(APP_DIR, 'scripts/subs/subs_domain.sh'),
  };
}
