import fs from 'node:fs/promises';
import path from 'node:path';
import { eq } from 'drizzle-orm';
import type { AgentPlatform } from '@shulkr/shared';
import { db } from '@shulkr/backend/db';
import { servers } from '@shulkr/backend/db/schema';
import { SERVERS_BASE_PATH } from '@shulkr/backend/services/paths';
import { serverProcessManager } from '@shulkr/backend/services/server_process_manager';
import { enableAgent, regenerateAgentToken, getServerAgent } from '@shulkr/backend/services/agent_token_service';
import { getEmbeddedJarPath } from '@shulkr/backend/services/agent_version_service';

export type InstallResult =
  | {
      success: true;
      jarPath: string;
      configPath: string;
      restartRequired: boolean;
    }
  | {
      success: false;
      error: 'server_not_found' | 'jar_missing' | 'path_unsafe' | 'write_failed';
      message?: string;
    };

function getBackendUrl(): string {
  return process.env.SHULKR_AGENT_BACKEND_URL ?? 'http://127.0.0.1:3001';
}

function buildConfigYaml(opts: { backendUrl: string; serverId: string; token: string }): string {
  return `# shulkr-core configuration
# This file is managed by the shulkr panel; manual edits may be overwritten on reinstall.

# URL of the shulkr backend
backend_url: ${opts.backendUrl}

# Identifier of this server, as known by shulkr
server_id: ${opts.serverId}

# Authentication token (generated by the panel — never share)
token: ${opts.token}

# How often to push metrics (seconds)
push_interval_seconds: 5

# Protocol version (do not edit unless shulkr requires it)
protocol_version: 1
`;
}

async function ensureSafePath(serverPath: string): Promise<string> {
  const resolved = path.resolve(serverPath);
  const base = path.resolve(SERVERS_BASE_PATH);
  if (!resolved.startsWith(base)) {
    throw new Error('path_unsafe');
  }
  return resolved;
}

export async function installAgent(serverId: string, platform: AgentPlatform): Promise<InstallResult> {
  const [server] = await db.select().from(servers).where(eq(servers.id, serverId)).limit(1);
  if (!server) return { success: false, error: 'server_not_found' };

  let resolvedServerPath: string;
  try {
    resolvedServerPath = await ensureSafePath(server.path);
  } catch {
    return { success: false, error: 'path_unsafe' };
  }

  const jarSource = getEmbeddedJarPath(platform);
  const jarExists = await fs
    .stat(jarSource)
    .then(() => true)
    .catch(() => false);
  if (!jarExists) {
    return { success: false, error: 'jar_missing', message: jarSource };
  }

  // Regenerate token on every install to avoid stale configs
  const existing = await getServerAgent(serverId);
  const tokenBundle = existing ? await regenerateAgentToken(serverId) : await enableAgent(serverId, platform);
  // Persist the chosen platform and force enabled=true (reinstalling implies re-enabling,
  // otherwise a previously disabled agent would keep rejecting pushes with 403).
  if (existing) {
    const { sqlite } = await import('@shulkr/backend/db');
    sqlite
      .prepare(`UPDATE server_agents SET platform = ?, enabled = 1, updated_at = CURRENT_TIMESTAMP WHERE server_id = ?`)
      .run(platform, serverId);
  }

  // All 4 platforms use a `plugins/` folder (Paper/Folia/Velocity/Waterfall all do).
  const pluginsDir = path.join(resolvedServerPath, 'plugins');
  const configDir = path.join(pluginsDir, 'shulkr-core');
  const jarDest = path.join(pluginsDir, `shulkr-core-${platform}.jar`);
  const configPath = path.join(configDir, 'config.yml');

  try {
    await fs.mkdir(pluginsDir, { recursive: true });
    await fs.mkdir(configDir, { recursive: true });
    await fs.copyFile(jarSource, jarDest);
    await fs.writeFile(
      configPath,
      buildConfigYaml({
        backendUrl: getBackendUrl(),
        serverId,
        token: tokenBundle.token,
      }),
      'utf8'
    );
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : 'unknown';
    return { success: false, error: 'write_failed', message };
  }

  const running = serverProcessManager.getRunningServers().includes(serverId);
  return {
    success: true,
    jarPath: jarDest,
    configPath,
    restartRequired: running,
  };
}
