import { join } from 'node:path';
import { DEFAULT_JAVA_PORT } from '@shulkr/shared';
import { type AppDeps } from '@shulkr/backend/deps';

function generateServerProperties(options: { serverName: string; port: number; motd?: string }): string {
  return `#Minecraft server properties
#Generated by Shulkr
enable-jmx-monitoring=false
rcon.port=25575
level-seed=
gamemode=survival
enable-command-block=false
enable-query=false
generator-settings={}
enforce-secure-profile=true
level-name=world
motd=${options.motd || options.serverName}
query.port=${options.port}
pvp=true
generate-structures=true
max-chained-neighbor-updates=1000000
difficulty=easy
network-compression-threshold=256
max-tick-time=60000
require-resource-pack=false
use-native-transport=true
max-players=20
online-mode=true
enable-status=true
allow-flight=false
initial-disabled-packs=
broadcast-rcon-to-ops=true
view-distance=10
server-ip=
resource-pack-prompt=
allow-nether=true
server-port=${options.port}
enable-rcon=false
sync-chunk-writes=true
op-permission-level=4
prevent-proxy-connections=false
hide-online-players=false
resource-pack=
entity-broadcast-range-percentage=100
simulation-distance=10
rcon.password=
player-idle-timeout=0
force-gamemode=false
rate-limit=0
hardcore=false
white-list=false
broadcast-console-to-ops=true
spawn-npcs=true
spawn-animals=true
log-ips=true
function-permission-level=2
initial-enabled-packs=vanilla
level-type=minecraft\\:normal
text-filtering-config=
spawn-monsters=true
enforce-whitelist=false
spawn-protection=16
resource-pack-sha1=
max-world-size=29999984
`;
}

export interface ServerSetupOptions {
  serverPath: string;
  serverName: string;
  javaPort?: number;
}

type Deps = Pick<AppDeps, 'fs'>;

async function createEula(deps: Deps, serverPath: string): Promise<void> {
  const eulaContent = `#By changing the setting below to TRUE you are indicating your agreement to our EULA (https://aka.ms/MinecraftEULA).
#Generated by Shulkr
eula=true
`;
  await deps.fs.writeFile(join(serverPath, 'eula.txt'), eulaContent);
}

async function createServerProperties(
  deps: Deps,
  serverPath: string,
  options: { serverName: string; port: number }
): Promise<void> {
  await deps.fs.writeFile(join(serverPath, 'server.properties'), generateServerProperties(options));
}

export async function initializeServer(deps: Deps, options: ServerSetupOptions): Promise<void> {
  const { serverPath, serverName, javaPort = DEFAULT_JAVA_PORT } = options;
  await deps.fs.mkdir(serverPath, { recursive: true });
  await Promise.all([createEula(deps, serverPath), createServerProperties(deps, serverPath, { serverName, port: javaPort })]);
}

export async function updateServerPort(deps: Deps, serverPath: string, port: number): Promise<void> {
  const filePath = join(serverPath, 'server.properties');
  try {
    let content = await deps.fs.readFileText(filePath);
    content = content.replace(/^server-port=\d+$/m, `server-port=${port}`);
    content = content.replace(/^query\.port=\d+$/m, `query.port=${port}`);
    await deps.fs.writeFile(filePath, content);
  } catch {}
}
